#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "webhook"
name = "Webhook"
description.en = "Webhook server to run shell commands."
description.fr = "Serveur webhook pour lancer des commandes shell."

version = "2.8.1~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
admindoc = "https://github.com/adnanh/webhook/tree/master/docs"
code = "https://github.com/adnanh/webhook"
fund = "https://github.com/adnanh/webhook?tab=readme-ov-file#by-giving-money"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "12M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/adnanh/webhook/releases/download/2.8.1/webhook-linux-amd64.tar.gz"
    amd64.sha256 = "15e13ab8ee5b6dfbc9423e732c9b28728e0aa1afb033e481561e76b2be1170a9"
    i386.url = "https://github.com/adnanh/webhook/releases/download/2.8.1/webhook-linux-386.tar.gz"
    i386.sha256 = "f5d232160b0c87f6fe226095792e0681635f1ff33090b263ef595274f98395ff"
    armhf.url = "https://github.com/adnanh/webhook/releases/download/2.8.1/webhook-linux-arm.tar.gz"
    armhf.sha256 = "59977d3941390f71443a8b914c87d076f1b2a59deb30d3acfba151d3d9b0d698"
    arm64.url = "https://github.com/adnanh/webhook/releases/download/2.8.1/webhook-linux-arm64.tar.gz"
    arm64.sha256 = "51d077b3ba5678a88e4a5e28d4127a3cfde4d1b5284ec03a4ec95a7852d64202"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^webhook-linux-amd64.tar.gz$"
    autoupdate.asset.i386 = "^webhook-linux-386.tar.gz$"
    autoupdate.asset.armhf = "^webhook-linux-arm.tar.gz$"
    autoupdate.asset.arm64 = "^webhook-linux-arm64.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]
