#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "webhook"
name = "Webhook"
description.en = "Server to run Webhook shell commands"
description.fr = "Serveur webhook pour lancer des commandes shell"

version = "2.8.3~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
admindoc = "https://github.com/adnanh/webhook/tree/master/docs"
code = "https://github.com/adnanh/webhook"
fund = "https://github.com/adnanh/webhook?tab=readme-ov-file#by-giving-money"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "10M"
ram.build = "80M"
ram.runtime = "40M"

[install]
    [install.domain]
    type = "domain"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/adnanh/webhook/releases/download/2.8.3/webhook-linux-amd64.tar.gz"
    amd64.sha256 = "3cdf93f0615f11bfc575c158d0d613666394228f6e830ff6f792178933773f7b"
    arm64.url = "https://github.com/adnanh/webhook/releases/download/2.8.3/webhook-linux-arm64.tar.gz"
    arm64.sha256 = "960187f361ca49403e0d3fce546c0a1999095a4ee6934a57ab8fef3170f2ddc8"
    armhf.url = "https://github.com/adnanh/webhook/releases/download/2.8.3/webhook-linux-arm.tar.gz"
    armhf.sha256 = "7e2548a77e9721a4e3f69ec2d2aa291b1cd64aaebc3510c389339e65986cab98"
    i386.url = "https://github.com/adnanh/webhook/releases/download/2.8.3/webhook-linux-386.tar.gz"
    i386.sha256 = "c85230a1f4399e06355cbc83b1c6f27d118df7c1cc9b05c8b934eecc74894265"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^webhook-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^webhook-linux-arm64.tar.gz$"
    autoupdate.asset.armhf = "^webhook-linux-arm.tar.gz$"
    autoupdate.asset.i386 = "^webhook-linux-386.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]
