#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "webhook"
name = "Webhook"
description.en = "Server to run Webhook shell commands"
description.fr = "Serveur webhook pour lancer des commandes shell"

version = "2.8.2~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
admindoc = "https://github.com/adnanh/webhook/tree/master/docs"
code = "https://github.com/adnanh/webhook"
fund = "https://github.com/adnanh/webhook?tab=readme-ov-file#by-giving-money"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "10M"
ram.build = "80M"
ram.runtime = "40M"

[install]
    [install.domain]
    type = "domain"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/adnanh/webhook/releases/download/2.8.2/webhook-linux-amd64.tar.gz"
    amd64.sha256 = "7a190ec7b4c2ffbb4eb1e11755a2e7acd82f1ffe74f60f235a360441daf22fd2"
    arm64.url = "https://github.com/adnanh/webhook/releases/download/2.8.2/webhook-linux-arm64.tar.gz"
    arm64.sha256 = "0ff4b0d0b411869407bd3b4727559c008c62779801a139f80b5ac2b06144aa11"
    armhf.url = "https://github.com/adnanh/webhook/releases/download/2.8.2/webhook-linux-arm.tar.gz"
    armhf.sha256 = "0b592a0a63e48497a37188c57c5cee672c40c35221e3279efd0d1b4eb366e45b"
    i386.url = "https://github.com/adnanh/webhook/releases/download/2.8.2/webhook-linux-386.tar.gz"
    i386.sha256 = "6c54b29a318d10979ec25be50a920ab92890e0a3c8bfd183f1ad6595dfd85725"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^webhook-linux-amd64.tar.gz$"
    autoupdate.asset.arm64 = "^webhook-linux-arm64.tar.gz$"
    autoupdate.asset.armhf = "^webhook-linux-arm.tar.gz$"
    autoupdate.asset.i386 = "^webhook-linux-386.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]
